### ISSUE TITLE
Implement story scraping

### ISSUE THREAD

**Issue by NiGhTTraX** [NiGhTTraX/hackernews-scraper#2]
## Need

I want to be able to fetch stories created since a timestamp.
## Deliverables

``` gherkin
Scenario: Scraping stories
Given I have a timestamp
When I call the scraper
Then it will return all the stories created since that timestamp
```

``` gherkin
Scenario: Scraping too many stories
Given I have a timestamp
And there are more than 50 * 20 stories since that timestamp
When I call the scraper
Then it will return all the stories created since that timestamp
And throw an exception informing me that there are more stories left that couldn't be fetched by the API
```

``` gherkin
Scenario: No stories since timestamp
Given I have a timestamp
And there aren't any new stories since that timestamp
When I call the scraper
Then it will return an empty iterator
```

A returned story could look like this

``` json
{
"created_at": "2014-03-05T17:12:12.000Z",
"title": "Are You the Best Person to Lead Your Startup?",
"url": "http://startupcollective.com/are-you-the-best-person-to-lead-your-startup",
"author": "ryanpaugh",
"points": 1,
"story_text": "Sometimes, following can be the most productive form of leadership.",
"timestamp": 1394039532,
"story_id": "7348156"
}
```
#### Prerequisites
- glance over [the hacker news section](https://news.ycombinator.com/)
- [Algolia hacker news API](http://hn.algolia.com/api)
#### TODO
- [x] Implement story scraping
- [x] Implement fetching stories newer than a given timestamp
#### Testing

Use mocking for response handling
- [x] all fields are returned
- [x] going back more than the supported number of pages raises an Exception
- [x] when the API doesn't return anything, nothing is yielded and it doesn't break the code 
#### Notes
- [ ] What should I do if the response is missing fields? Fail silently or raise KeyError??
